### ISSUE TITLE
命令问题

### ISSUE THREAD

**Issue by XRRXRRXRRXRR** [MinatoAquaCrews/nonebot_plugin_fortune#11]
请问超管的刷新抽签怎么命令

**Comment by KafCoppelia** [comment]
直接`刷新抽签`，或者`/刷新抽签`？🤔取决于你的`COMMAND_START`

**Comment by XRRXRRXRRXRR** [comment]
谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月21日(星期一) 上午7:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MinatoAquaCrews/nonebot_plugin_fortune] 命令问题 (Issue #11)





 
直接刷新抽签，或者/刷新抽签？🤔取决于你的COMMAND_START
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
