### ISSUE TITLE
如果有两个跑了一样插件的机器人会出现并发

### ISSUE THREAD

**Issue by MoYoez** [MinatoAquaCrews/nonebot_plugin_fortune#16]
![-69f8fee9c2d7dd97.jpg](https://user-images.githubusercontent.com/30306672/172259548-2cd1a95b-7576-4bfe-99ba-0ad68ea29253.jpg)
这样 会一直刷 希望可以解决这个问题

**Comment by KafCoppelia** [comment]
是正则匹配条件给大了，可以：
1. 改“还不可以指定这种签哦……”为“指定失败，……”（反正不要出现指定xx签句型）；
2. 改插件`__init__.py`下`r"指定(.*?)签"`为`r"^指定(.*?)签&"`

**Comment by MoYoez** [comment]
好的 谢谢

**Comment by KafCoppelia** [comment]
[v0.4.4](https://github.com/MinatoAquaCrews/nonebot_plugin_fortune/releases/tag/v0.4.4)以上版本已修改
