### ISSUE TITLE
考虑新增命令”抽pcr签“

### ISSUE THREAD

**Issue by NepPure** [MinatoAquaCrews/nonebot_plugin_fortune#18]
pcr抽签、原神抽签

是不是更方便，群友自己选择

**Comment by KafCoppelia** [comment]
大聪明，我怎么没想到呢？！

**Comment by KafCoppelia** [comment]
再等一下，今晚发`v0.4.4a2`更新了此项功能

**Comment by KafCoppelia** [comment]
[vo.4.4a2](https://github.com/MinatoAquaCrews/nonebot_plugin_fortune/releases/tag/v0.4.4a2)已添加此命令
