### ISSUE TITLE
启用和关闭随机抽签主题的配置失效

### ISSUE THREAD

**Issue by jiana3** [MinatoAquaCrews/nonebot_plugin_fortune#27]
插件加载成功可以发送抽签结果，但是无论是在`env`或者`config.py`修改部分主题为`false`，关闭的主题在随机抽签时依然会出现。

我尝试定位问题，发现运行到`utils.py`下的`def randomBasemap`时，始终不会进入`if MainThemeEnable.get(picked_theme) is True`这一判断语句。
于是我试着在循环完成后输出`try_time`和`MainThemeEnable.get(picked_theme)`的值，结果分别是`21`和`None`。
看来是程序在运行时尝试了所有主题都不满足条件于是选择了随机到的最后一个主题，因此关闭的主题依然会出现在随机抽签结果中。
不清楚`MainThemeEnable.get(picked_theme)`的值一直是`None`是我的设置问题还是bug。

**Comment by KafCoppelia** [comment]
确实是一个严重的bug，经过测试是遍历`resource/img`下主题文件夹的`theme`(`List[str]`)值不只是文件夹名，而是文件夹绝对路径，比如我希望得到：`hololive`，但实际上是`/home/username/fortune/resource/img/hololive`，导致`picked`值不对。

其次（虽然这个也是错的，但是前一个错误导致第二个正确与否都无法改变后续结果），`picked_theme`没必要加`_flag`，主题开启字典`MainThemeEnable`的键值我可能简化了，但是这里忘记去掉。

临时修改方法：原`utils.py` Line 66~73改为：
```
themes: List[str] = [str(f.name) for f in __p.iterdir() if f.is_dir()]
while True:
    picked = random.choice(themes)
    if MainThemeEnable.get(picked) is True:
        break
    else:
        try_time += 1

    if try_time == len(list(MainThemeEnable)):
        break
```
明日如果我有时间，会和文案资源一起更新一下。

**Comment by KafCoppelia** [comment]
试试[v0.4.5](https://github.com/MinatoAquaCrews/nonebot_plugin_fortune/releases/tag/v0.4.5)

**Comment by jiana3** [comment]
更新到 v0.4.6 后没问题了，辛苦了

**Comment by KafCoppelia** [comment]
> 更新到 v0.4.6 后没问题了，辛苦了

 v0.4.6存在bug，请尽快升级至[v0.4.7](https://github.com/MinatoAquaCrews/nonebot_plugin_fortune/releases/tag/v0.4.7)

**Comment by jiana3** [comment]
谢谢提醒，已升级到v0.4.8
