### ISSUE TITLE
【报错】今日运势生成出错……

### ISSUE THREAD

**Issue by Z735803792** [MinatoAquaCrews/nonebot_plugin_fortune#29]
操作过程：某一个群，先设置了夏日口袋签，然后就抽不了了，重新设置其他签也不行。
               但是其他没设置过的普通群都正常，终端无任何报错或警告
python3.9.12,nonebot2.0.0b4
![image](https://user-images.githubusercontent.com/70925546/180352585-92e07846-9312-46c6-af26-20959c425d7a.png)

**Comment by KafCoppelia** [comment]
确实有bug，先尝试一下[v0.4.5](https://github.com/MinatoAquaCrews/nonebot_plugin_fortune/releases/tag/v0.4.5)

**Comment by Z735803792** [comment]
更新v0.4.6了，现在其他功能正常，只是不能用指令“设置xx签”
“主题列表”指令后，显示没有主题。。
![image](https://user-images.githubusercontent.com/70925546/180616956-602e168b-1347-4e2d-8c39-9c9ed3bdf58b.png)

**Comment by KafCoppelia** [comment]
[v0.4.7](https://github.com/MinatoAquaCrews/nonebot_plugin_fortune/releases/tag/v0.4.7)已修复，v0.4.5改动比较多人搞晕了，留了一堆bug刷了俩版号

**Comment by Death-Star-Glory** [comment]
4.8版本，但是在没有任何设置的情况下，依旧存在生成失败的bug

**Comment by Z735803792** [comment]
无法更新4.8
![image](https://user-images.githubusercontent.com/70925546/181396871-6baad115-41af-4977-b5d2-ca22ad5b05d8.png)

**Comment by KafCoppelia** [comment]
> 无法更新4.8 ![image](https://user-images.githubusercontent.com/70925546/181396871-6baad115-41af-4977-b5d2-ca22ad5b05d8.png)

啊嗯，pypi上确实有0.4.8发布了，清华源全责

**Comment by Z735803792** [comment]
换阿里源解决了，谢谢大佬~
