### ISSUE TITLE
关于PIL库已经不受支持的问题

### ISSUE THREAD

**Issue by PrayRayleigh** [MinatoAquaCrews/nonebot_plugin_fortune#35]
PIL库已经无法被引用,当我试图运行pip install PIL时,找不到指定的包
希望作者能更新为最新的Pillow库

**Comment by KafCoppelia** [comment]
我依赖里写的是`pillow = "^9.0.0"`，至于为啥是：
```python
from PIL import ...
```
这是`pillow`库的历史遗留问题好像

**Comment by PrayRayleigh** [comment]
PIL是Pillow库的前身

**Comment by KafCoppelia** [comment]
但似乎即使是最新的`pillow 9.2.0`，其调用方法也是如此。参见[Pillow documentation](https://pillow.readthedocs.io/en/stable/handbook/tutorial.html#using-the-image-class)

**Comment by PrayRayleigh** [comment]
好的,我在另外一台计算机上没有出现类似问题.
