### ISSUE TITLE
插件加载成功但是没有图片

### ISSUE THREAD

**Issue by Waww5** [MinatoAquaCrews/nonebot_plugin_fortune#37]

**Comment by Waww5** [comment]
![UE8TMZI_ 8_KD``DM0 C)WR](https://user-images.githubusercontent.com/112326526/187074924-966d8c13-0205-4848-b6d2-4f70c1eb4fbe.png)

**Comment by Waww5** [comment]
![QQ截图20220828205131](https://user-images.githubusercontent.com/112326526/187074967-458c9f23-cb5f-4b29-b2ef-7bf48e2ceeed.png)

**Comment by KafCoppelia** [comment]
你咋不去`nonebot_plguin_tarot`底下问，是不是缺少图片素材

**Comment by Waww5** [comment]
![QQ截图20220828205131](https://user-images.githubusercontent.com/112326526/187080511-ed8f6247-229e-4af6-b88a-04b515f91961.png)
![QQ截图20220828225644](https://user-images.githubusercontent.com/112326526/187080513-c88c00de-ea3f-40ad-909a-2d89d5406dfd.png)
![QQ截图20220828225716](https://user-images.githubusercontent.com/112326526/187080515-48c82718-c384-44e2-acb3-653f7ae9b99b.png)

**Comment by Waww5** [comment]
从开始到第一张图片的输入反馈都截了

**Comment by KafCoppelia** [comment]
额，从头到尾我都只看到`nonebot_plugin_fortune`，但你却在问`nonebot_plguin_tarot`的命令怎么没反应

**Comment by Waww5** [comment]
我只是想表达后续没有图片产生

**Comment by Waww5** [comment]
![QQ截图20220829011408](https://user-images.githubusercontent.com/112326526/187086388-2822afe0-d834-4213-86c6-228b4ee8e1c0.png)
![QQ截图20220829011458](https://user-images.githubusercontent.com/112326526/187086391-4ba35cdc-dcba-4086-8986-05683b78b6c0.png)
补了效果图

**Comment by KafCoppelia** [comment]
`pypi`无法发行过大安装包，由此安装的插件不包含`resource/img`下所有抽签主题图片，需单独下载，建议zip包下载后单独提取`resource/img`抽签主题图片，后更改`FORTUNE_PATH`配置即可。

认真看看插件的说明文档，写得非常详细

**Comment by Waww5** [comment]
![QQ截图20220829161948](https://user-images.githubusercontent.com/112326526/187156995-5f81186c-b59b-4f2b-9930-e222a50c1c18.png)
已经下载了，我是用zip安装的

**Comment by KafCoppelia** [comment]
bot没有任何被插件响应的话，看看你的`COMMAND_START`有没有设置？参见nb指南

**Comment by Waww5** [comment]
是这个问题，已解决，感谢，因为两个插件都安了截图放错了私密嘛三！
