### ISSUE TITLE
今日运势生成出错……

### ISSUE THREAD

**Issue by Yuelioi** [MinatoAquaCrews/nonebot_plugin_fortune#39]
系统:centos
运行环境:ATRI 机器人
插件版本:0.4.8

文件目录

└─ data
──└─fortune
────└ font
────└ fortune
────└ img

配置信息:"FORTUNE_PATH":"./data/fortune"

---
结果:
输入 主题列表 可以成功生成列表
输入 抽取 返回 今日运势生成出错……

**Comment by KafCoppelia** [comment]
是不是没下载图片资源到指定路径？参见readme

**Comment by Yuelioi** [comment]
> 是不是没下载图片资源到指定路径？参见readme

下载过了的..
img文件夹下面21个子文件夹 然后每个文件夹里面一堆图片

难道不是这种结构么
└─ data
──└─fortune
────└ font
────└ fortune
────└ img
─────└amazing_grace(一堆图片)

**Comment by KafCoppelia** [comment]
配置是否正确？
```python
FORTUNE_PATH"="./data/fortune"
```

**Comment by Yuelioi** [comment]
> 配置是否正确？
> 
> ```python
> FORTUNE_PATH"="./data/fortune"
> ```

在ATRI robot里 env的配置项书写方式确实是这样的. 我问问原作者吧 也许不是插件的问题
