### ISSUE TITLE
这是不是没有适配nb的版本造成的啊

### ISSUE THREAD

**Issue by uuKhost** [MinatoAquaCrews/nonebot_plugin_fortune#45]
如图
![图片](https://user-images.githubusercontent.com/115860525/195996796-b95cb462-b512-4d3a-b616-e95c924848c9.png)

**Comment by KafCoppelia** [comment]
rc1的适配在做了~~，话说为啥升级nb2这么快啊？~~

**Comment by uuKhost** [comment]
我也不太明白口牙，最近才开始搞这个bot，也看不太懂报错，所以来问一下是不是真的是适配的问题，总之辛苦大佬们做这么好的插件了~

**Comment by llllin2333** [comment]
俺也更新了，一堆插件失效了2333

**Comment by KafCoppelia** [comment]
> 俺也更新了，一堆插件失效了2333

可以先把nonebot2回退到`beta5`版本，因为`rc1`有很多破坏性更新，而插件还没适配上

**Comment by CCYellowStar** [comment]
只要state: T_State = State()换成state: T_State就能用了

**Comment by KafCoppelia** [comment]
> 只要state: T_State = State()换成state: T_State就能用了

别急，这几天会搞出新版本来的

**Comment by ShanShuWu** [comment]
萌新问一手,如何退回到b5？？？

**Comment by KafCoppelia** [comment]
> 萌新问一手,如何退回到b5？？？

[安装Nonebot2](https://v2.nonebot.dev/docs/start/installation)，安装的时候指定版本即可

**Comment by KafCoppelia** [comment]
v0.4.9已适配rc1
