### ISSUE TITLE
适配版本

### ISSUE THREAD

**Issue by 1409109991** [MinatoAquaCrews/nonebot_plugin_fortune#50]
现在rc2加这个插件会让定时任务报错，这个插件也用不了
![image](https://user-images.githubusercontent.com/79674967/205866115-31a81bd2-30de-42e5-b506-334b640f76ca.png)

**Comment by 1409109991** [comment]
应该是我虚拟环境的问题，解决了

**Comment by KafCoppelia** [comment]
定时插件确实经历了一个破坏性更新，导致需要的nb2版本也要提高，目前可以将就一下在nb2 `2.0.0b5`，apscheduler `0.1.4`应该是没问题的。

在适配了在适配了，有时间我就搞……😭
