### ISSUE TITLE
有关apscheduler插件的报错-求解决办法

### ISSUE THREAD

**Issue by YouYouLip** [MinatoAquaCrews/nonebot_plugin_fortune#51]
![CHKEMF5H%YKUYN7TFDM(W$4](https://user-images.githubusercontent.com/119958263/207400616-10c15d1b-d379-4130-81f9-bd11ae9b1f36.png)

如图 请问这种办法怎么解决 我用的是python3.10.8版本 nb安装 我简单的审视了一下 是指我的apscheduler插件和此插件所需的apscheduler版本不兼容么？ 我尝试过使用apscheduler升级 但是吧... 还是显示和我有报错 求解决办法
![)7E6U1~6AMTR2UB~@JAN%JG](https://user-images.githubusercontent.com/119958263/207401291-fb8c9bff-e5a3-44c2-9648-9408c78fc144.png)

**Comment by YouYouLip** [comment]
如果无视这个报错直接运行bot的话 会显示此插件以导入但是后续会有这个报错
![H8NK~}9Z3 MA%XNS`G8G5$2](https://user-images.githubusercontent.com/119958263/207402322-adf4bb89-bde6-4937-8dc9-7d00516c6f65.png)

**Comment by YouYouLip** [comment]
已解决，我通过nb安装此插件后升级了apscheduler2.0 用nb安装次插件会直接给我安装apscheduler1.4版本导致我整个需要2.0的插件无法加载崩溃 env.pord后面把仓库中img相关的图片放到resources下并且指向环境变量即可解决

**Comment by KafCoppelia** [comment]
所以这个插件使用apscheduler `2.0` 版本不会有问题么？#48

**Comment by YouYouLip** [comment]
> 所以这个插件使用apscheduler `2.0` 版本不会有问题么？#48

至少我没有碰到 我总感觉是我没有配置环境变量或者img相关文件之前没有放之类的 并没有出现无法使用的情况 所有指令都可以触发

**Comment by YouYouLip** [comment]
> 所以这个插件使用apscheduler `2.0` 版本不会有问题么？#48

OK啊作者 碰上问题了 apscheduler会报错 问了一个人 说是报错原因是这个，弱弱的问一句会考虑apscheduler向上兼容么（反正apscheduler确实会有问题...）
![RHQ3`H@PWBAL~UGZ_4PHNCA](https://user-images.githubusercontent.com/119958263/209072196-d6cc808c-2ad8-41f3-9a04-28b58969d69d.png)
这个问题是我熄屏后才会出现 就是一大早挂上bot到晚上2 3点都没事 但是熄显示屏运行后就会出现bot显示Job "check_bili_live (trigger: interval[0:01:00], next run at: 2022-12-22 07:23:16 CST)" raised an exception并且gocq也会掉线（这个问题仅限我熄屏后出现 不熄屏不会出现）

**Comment by YouYouLip** [comment]
> > 所以这个插件使用apscheduler 版本不会有问题么？#48`2.0`
> 
> OK啊作者 碰上问题了 apscheduler会报错 问了一个人 说是报错原因是这个，弱弱的问一句会考虑apscheduler向上兼容么（反正apscheduler确实会有问题...） ![RHQ3`H@PWBAL~UGZ_4PHNCA](https://user-images.githubusercontent.com/119958263/209072196-d6cc808c-2ad8-41f3-9a04-28b58969d69d.png) 这个问题是我熄屏后才会出现 就是一大早挂上bot到晚上2 3点都没事 但是熄显示屏运行后就会出现bot显示作业“check_bili_live （触发器：interval[0：01：00]，下一次运行时间：2022-12-22 07：23：16 CST）” 引发异常并且gocq也会掉线（这个问题仅限我熄屏后出现 不熄屏不会出现）

鹅 不对 搞错了！不是该插件的毛病 抱歉忘检查其他依赖apscheduler的插件了
