### ISSUE TITLE
利用nonebot2下载时，如果安装环境为nonebot-plugin-apscheduler==2.0.0会报错

### ISSUE THREAD

**Issue by SCUOP** [MinatoAquaCrews/nonebot_plugin_fortune#52]
nb plugin install nonebot-plugin-fortune安装时，会显示nonebot-plugin-apscheduler==2.0.0依赖冲突，但是实际不冲突，可以使用，爆红看着很不舒服。

**Comment by KafCoppelia** [comment]
emmmmmm 有时间我会提高插件依赖的……

**Comment by KafCoppelia** [comment]
[v0.4.10](https://github.com/MinatoAquaCrews/nonebot_plugin_fortune/releases/tag/v0.4.10)
