### ISSUE TITLE
Resource Manelon.otf is missing...

### ISSUE THREAD

**Issue by shelter132** [MinatoAquaCrews/nonebot_plugin_fortune#53]
运行时插件模块未报错，但好像插件自带的检测功能报错。重新检查了resource文件夹，字体文件没有丢失，但始终报错。不知道是不是dev里的resource位置写错了，求大佬指教。
![XF~WB%NC_Y1KC)T_H9ZMPWK](https://user-images.githubusercontent.com/99066443/209068134-2c7e421c-a750-409b-8e28-b927dc947316.png)
![~R1FJO91@@IM`O5Z@B)3DV4](https://user-images.githubusercontent.com/99066443/209068454-33d500e9-2046-4a15-af84-8c871d8066f1.png)
![RDWR 63K (@4L0KS}4%W$_B](https://user-images.githubusercontent.com/99066443/209068483-905b8230-c766-4ae1-83d2-6444d13a7915.png)

**Comment by shelter132** [comment]
这是dev里的path
![6J3~6BOC U0W$LIXXS81$8](https://user-images.githubusercontent.com/99066443/209069161-c6b686fe-6eb4-4ca1-a22d-7070727a390a.png)

**Comment by KafCoppelia** [comment]
哈哈哈
