### ISSUE TITLE
新增自定义主题失败，fortune_config.json总是自动恢复

### ISSUE THREAD

**Issue by LiberatorHg** [MinatoAquaCrews/nonebot_plugin_fortune#60]
1.我在（自定义的资源路径）/my-data/fortune/img下已经添加主题素材
2./my-data/fortunefortune_setting.json下已配置图片对应的路径
3.已在config.py中设置对应的 xxx_flag 并启用，
4.env.prod 也开启了对应的 主题

求教 为啥每次重启bot后**fortune_config.json**会把我的主题flag清除

**Comment by KafCoppelia** [comment]
按照[How-to-add-new-theme](https://github.com/MinatoAquaCrews/nonebot_plugin_fortune/blob/master/How-to-add-new-theme.md)操作。

在`v0.4.10`及以后的版本中，不会生成`fortune_config.json`文件了。好像在之前的版本里，生成的`fortune_config.json`也没什么用……
