### ISSUE TITLE
关于qq群匿名者共用一个签的问题

### ISSUE THREAD

**Issue by KidJoe1412** [MinatoAquaCrews/nonebot_plugin_fortune#62]
不知道能否改进一下判断机制，如果是匿名的话，根据匿名的名字来区分不同的用户

**Comment by KidJoe1412** [comment]
这只是一个建议，因为这个操作可能会对已有项目造成较大冲击

**Comment by KafCoppelia** [comment]
目前插件储存信息是按QQ号来的，匿名用户均为`80000000`，确实会导致判断错误。如果要解决的话，最简单的方法是多储存用户名，但是这样会增加较目前一倍的数据量。

况且，区分了匿名，用户退出匿名后还是能抽签，实际上也没有对用户进行**真实地记录**

**Comment by KafCoppelia** [comment]
或者说，直接不响应匿名QQ号抽签的命令。感觉很鸡肋，几乎没看到有群在匿名聊天，但是也可以加上这个限制功能

**Comment by HelloLiNing** [comment]
那qq群匿名可以查到是谁不，感谢大哥们回复

**Comment by KafCoppelia** [comment]
> 那qq群匿名可以查到是谁不，感谢大哥们回复

匿名用户的QQ均为80000000，因此无法查到具体身份

**Comment by HelloLiNing** [comment]
我们同学在班级qq群匿名和老师对骂了，老师说让自己来承认，不然动用一切技术手段查这个同学，这样的情况。就怕被查到，谢谢大哥们

**Comment by KafCoppelia** [comment]
呃你这个问题为什么在我这一个插件的issue里问呢？

**Comment by HelloLiNing** [comment]
想问问懂底层原理的人哈哈哈哈哈，从原理来讲能不能实现这样子。。。打扰大家了，实属冒昧
