### ISSUE TITLE
今日运势生成出错……

### ISSUE THREAD

**Issue by Wexevou** [MinatoAquaCrews/nonebot_plugin_fortune#66]
![图片](https://user-images.githubusercontent.com/117566653/227784878-762ec381-73d0-477d-bc7b-0664bc8af65a.png)
![图片](https://user-images.githubusercontent.com/117566653/227784896-a0a78597-ae86-4aa3-be2e-c87245eb0848.png)
![图片](https://user-images.githubusercontent.com/117566653/227784908-dd87f2d0-3770-4932-8a78-12d139836651.png)
看看是不是我哪里问题

**Comment by NanakoOfficial** [comment]
把目录写完整试试

**Comment by Wexevou** [comment]
> 把目录写完整试试

![图片](https://user-images.githubusercontent.com/117566653/227786396-8a713e72-7bf7-494f-a28f-779188c6db1a.png)
![图片](https://user-images.githubusercontent.com/117566653/227786411-616c6325-e231-49df-b3a9-6a5573ff27f0.png)
奇了个怪

**Comment by KafCoppelia** [comment]
你这路径……

**Comment by Wexevou** [comment]
> 

啊哈不管在哪个路径都这样
难道要py下的路径？

**Comment by NanakoOfficial** [comment]
> > 把目录写完整试试
> 
> ![图片](https://user-images.githubusercontent.com/117566653/227786396-8a713e72-7bf7-494f-a28f-779188c6db1a.png)
> ![图片](https://user-images.githubusercontent.com/117566653/227786411-616c6325-e231-49df-b3a9-6a5573ff27f0.png)
> 奇了个怪

派蒙bot我就不清楚了，我手动构建的目录写全可以正常用..

**Comment by Wexevou** [comment]
> > > 把目录写完整试试
> > 
> > 
> > ![图片](https://user-images.githubusercontent.com/117566653/227786396-8a713e72-7bf7-494f-a28f-779188c6db1a.png)
> > ![图片](https://user-images.githubusercontent.com/117566653/227786411-616c6325-e231-49df-b3a9-6a5573ff27f0.png)
> > 奇了个怪
> 
> 派蒙bot我就不清楚了，我手动构建的目录写全可以正常用..

只能一点点试了

**Comment by Wexevou** [comment]
> 你这路径……我估计大概率是路径问题

看下面 我路径改了 也不行吖

**Comment by Wexevou** [comment]
> > > 把目录写完整试试
> > 
> > 
> > ![图片](https://user-images.githubusercontent.com/117566653/227786396-8a713e72-7bf7-494f-a28f-779188c6db1a.png)
> > ![图片](https://user-images.githubusercontent.com/117566653/227786411-616c6325-e231-49df-b3a9-6a5573ff27f0.png)
> > 奇了个怪
> 
> 派蒙bot我就不清楚了，我手动构建的目录写全可以正常用..

现在出现行的问题 啧 你能不能解决呢？
![图片](https://user-images.githubusercontent.com/117566653/227788519-64a2a0b8-bb0d-4463-b31d-7b17b29823e6.png)

**Comment by Wexevou** [comment]
> > > 把目录写完整试试
> > 
> > 
> > ![图片](https://user-images.githubusercontent.com/117566653/227786396-8a713e72-7bf7-494f-a28f-779188c6db1a.png)
> > ![图片](https://user-images.githubusercontent.com/117566653/227786411-616c6325-e231-49df-b3a9-6a5573ff27f0.png)
> > 奇了个怪
> 
> 派蒙bot我就不清楚了，我手动构建的目录写全可以正常用..

解决了

**Comment by Wexevou** [comment]
> 你这路径……我估计大概率是路径问题

已解决 资源问题
