### ISSUE TITLE
机器人回复今日运势生成出错……

### ISSUE THREAD

**Issue by verynewabie** [MinatoAquaCrews/nonebot_plugin_fortune#69]
输出debug了好久，定位到问题在utils.py里的drawing函数中，打印出来异常信息是SFNT font table missing，实在不懂怎么搞，用的是centos7的服务器

**Comment by verynewabie** [comment]
今天又测试了下，有时候异常信息是SFNT font table missing，有时候是cannot identify image file 'xxxx'，但是路径是对的

**Comment by verynewabie** [comment]
我把title的字体改成text的字体就可以了，那估计是跟Mamelon字体有关，另外，我这里偶尔会报image file is truncated错误，好像是因为图片太大，加上如下代码就好了
```Python
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
```

**Comment by verynewabie** [comment]
然后我重下了Mamelon字体，结果标题没问题，但是text显示不全，有的字没了，然后又重装了一遍插件，没问题了，鼠鼠也不懂怎么解决的，反正是没问题了。

**Comment by KafCoppelia** [comment]
如果自用的抽签主题图片，大小是480*480

此外，遇到其他的生成报错，先考虑一下是不是缺少资源

**Comment by verynewabie** [comment]
我两次都是直接把整个文件夹直接拖到服务器里的，第一次就报错，第二次就好了，不管了，反正没问题了
