### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by yejunlee1231** [MinatoAquaCrews/nonebot_plugin_fortune#71]
请问可以让他只输出图不输出文字吗？
如何做到啊
谢谢

**Comment by KafCoppelia** [comment]
真是奇怪的需求……

修改如下函数，注释Line 60~100，未经过测试：
https://github.com/MinatoAquaCrews/nonebot_plugin_fortune/blob/8746cdbcead8ce83772e3d9d05d8c95cedadc991/nonebot_plugin_fortune/utils.py#L54
