### ISSUE TITLE
救命啊，好多指令不生效，而且它还骂我

### ISSUE THREAD

**Issue by zhulinyv** [MinatoAquaCrews/nonebot_plugin_fortune#79]
如图，我只有 `抽签`, `重置抽签主题`, `主题列表`, `查看抽签主题`可用,

 `xxx抽签`, `指定xxx签`, `设置xxx签`无效, 是因为大凶的原因嘛 QwQ...

插件版本: v0.4.10.post2

Nonebot版本: 2.0.0

![image](https://github.com/MinatoAquaCrews/nonebot_plugin_fortune/assets/66541860/6c826515-08f5-4d1c-8b63-652149e04116)

![image](https://github.com/MinatoAquaCrews/nonebot_plugin_fortune/assets/66541860/8ff30eac-bc2a-497b-aa66-e18b06bf81a1)

**Comment by KafCoppelia** [comment]
nb2 `2.0.0rc4` 及以上会出现这个现象，是一个breaking change引起的，具体是正则匹配 `RegexMatched` 的机制出现了变化。但作者几乎没时间维护……

For details, please see:

[Feature: `REGEX_MATCHED` 值由`matched.group()` 改为 `matched`](https://github.com/nonebot/nonebot2/pull/1453)
[Feature: 支持 `re.Match` 依赖注入](https://github.com/nonebot/nonebot2/pull/1950)

**Comment by zhulinyv** [comment]
https://github.com/MinatoAquaCrews/nonebot_plugin_fortune/pull/80
