### ISSUE TITLE
新主题

### ISSUE THREAD

**Issue by veadex** [MinatoAquaCrews/nonebot_plugin_fortune#87]
我和别人一起做了一个主题，能加进去吗？主题预览大概是这样，![-2cb2019b7a204fed.png](https://github.com/MinatoAquaCrews/nonebot_plugin_fortune/assets/65024689/0168824d-36c2-4881-b661-5dc4a8fb02d9)

现在一共有90多张图，还有一些没做完

**Comment by KafCoppelia** [comment]
欢迎欢迎🎉 也可以往[zbpdata](https://github.com/FloatTech/zbpdata/)贡献你的签底

**Comment by veadex** [comment]
等我晚上把最后几张搞完就pr一下
🥰

**Comment by veadex** [comment]
我已经提交pr了，你看看有没有什么问题

**Comment by KafCoppelia** [comment]
好的，预计明早更新一版

**Comment by veadex** [comment]
₍˄·͈༝·͈˄*₎◞ ̑̑❤️好

**Comment by KafCoppelia** [comment]
[`v0.4.12a1`](https://github.com/MinatoAquaCrews/nonebot_plugin_fortune/releases/tag/v0.4.12a1)，可以尝试一下效果。

我将所有有关 `WSGR` 名称的部分均修改为 `warship_girls_r`

**Comment by veadex** [comment]
好多，我试试

**Comment by veadex** [comment]
> [`v0.4.12a1`](https://github.com/MinatoAquaCrews/nonebot_plugin_fortune/releases/tag/v0.4.12a1)，可以尝试一下效果。
> 
> 我将所有有关 `WSGR` 名称的部分均修改为 `warship_girls_r`

现在还能加个人吗，做主题的时候底图是这个人设计的 @Исфахан ·Макаров

**Comment by veadex** [comment]
> [`v0.4.12a1`](https://github.com/MinatoAquaCrews/nonebot_plugin_fortune/releases/tag/v0.4.12a1)，可以尝试一下效果。
> 
> 我将所有有关 `WSGR` 名称的部分均修改为 `warship_girls_r`

所有指令都试了一下，全部都没问题
因为没有写指定角色签底，所以没有测试指定xx签

**Comment by KafCoppelia** [comment]
> > [`v0.4.12a1`](https://github.com/MinatoAquaCrews/nonebot_plugin_fortune/releases/tag/v0.4.12a1)，可以尝试一下效果。
> > 我将所有有关 `WSGR` 名称的部分均修改为 `warship_girls_r`
> 
> 现在还能加个人吗，做主题的时候底图是这个人设计的 @Исфахан ·Макаров

可以的，但是在我的仓库里艾特不上，因为提交的pr里没有他的commit，但我还是能艾特一下。

**Comment by veadex** [comment]
那就麻烦你at一下吧，这个是他的主页
@₍˄·͈༝·͈˄*₎◞ ̑̑
https://github.com/EsfahanMakarov

**Comment by KafCoppelia** [comment]
OK，已经加上艾特了

**Comment by veadex** [comment]
> OK，已经加上艾特了

麻烦大佬了_(:з」∠)_

**Comment by KafCoppelia** [comment]
[`v0.4.12`](https://github.com/MinatoAquaCrews/nonebot_plugin_fortune/releases/tag/v0.4.12)
